import { test, expect } from '@playwright/test';
test('cancelar y confirmar eliminación de un borrador abierto', async ({page}) => {
  await page.goto('/');
  const requirement='MD DELETE '+Date.now();
  await page.getByLabel('Requerimiento *',{exact:true}).fill(requirement);
  await page.getByRole('button',{name:'Guardar borrador'}).click();
  await expect(page.locator('.message.success').last()).toContainText('Borrador guardado');
  await page.getByLabel('Descripción del requerimiento *').fill('Cambios pendientes');
  await page.getByRole('button',{name:'Borradores locales'}).click();
  await page.getByLabel('Buscar borradores').fill(requirement);
  await page.getByRole('button',{name:'Buscar',exact:true}).click();
  const remove=page.getByRole('button',{name:`Eliminar documento ${requirement}`,exact:true});
  await remove.click();
  await expect(page.getByText('y se descartarán sus cambios sin guardar',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Cancelar',exact:true}).click();
  await expect(remove).toBeVisible();
  await remove.click();
  const response=page.waitForResponse(r=>r.request().method()==='DELETE');
  await page.getByRole('button',{name:'Eliminar definitivamente'}).click();
  expect((await response).status()).toBe(204);
  await expect(remove).toHaveCount(0);
  await expect(page.getByText(`Documento ${requirement} eliminado.`,{exact:true})).toBeVisible();
  await page.getByRole('dialog',{name:'Borradores locales',exact:true}).getByRole('button',{name:'Close',exact:true}).click();
  await expect(page.getByLabel('Requerimiento *',{exact:true})).toHaveValue('');
  await page.reload();
  await page.getByRole('button',{name:'Borradores locales'}).click();
  await page.getByLabel('Buscar borradores').fill(requirement);
  await page.getByRole('button',{name:'Buscar',exact:true}).click();
  await expect(page.locator('.history-item')).toHaveCount(0);
});
