import { test, expect } from '@playwright/test';
test('buscar borradores y guardar correo con formato y avisos fijos', async ({page}) => {
  const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.getByLabel('Requerimiento *',{exact:true}).fill('MD EDITOR 777');
  await page.getByLabel('Cliente',{exact:true}).fill('Cliente Editor Único');
  await page.getByLabel('Descripción del requerimiento *').fill('Descripción para búsqueda y correo');
  await page.getByRole('button',{name:'Preparar correo'}).click();
  const editor=page.locator('.ql-editor'); await expect(editor).toBeVisible();
  await editor.fill('Texto de correo personalizado');
  await editor.press('Control+a');
  await page.getByRole('button',{name:'Negrita',exact:true}).click();
  await expect(page.locator('.email-preview strong').filter({hasText:'Texto de correo personalizado'})).toHaveCount(1);
  await page.locator('.ql-font select, select.ql-font').selectOption('Georgia',{force:true});
  await page.locator('select.ql-size').selectOption('18pt',{force:true});
  await page.locator('select.ql-align').selectOption('justify',{force:true});
  await expect(page.locator('.email-preview p').filter({hasText:'Texto de correo personalizado'})).toHaveCSS('text-align','justify');
  await expect(page.locator('.email-preview [style*="Georgia"]').first()).toHaveCSS('font-family','Georgia');
  await expect(page.locator('.email-preview [style*="18pt"]').first()).toHaveCSS('font-size','24px');
  await expect(page.getByLabel('Aviso ambiental',{exact:true})).toHaveCount(0);
  await expect(page.locator('.email-preview')).toContainText('¡Salva un árbol');
  await page.getByRole('button',{name:'Guardar borrador'}).click();
  await expect(page.locator('.message.success').last()).toContainText('Borrador guardado');
  await page.reload();
  await page.getByRole('button',{name:'Borradores locales'}).click();
  await page.getByLabel('Buscar borradores').fill('cliente editor unico');
  await page.getByRole('button',{name:'Buscar',exact:true}).click();
  await expect(page.locator('.history-item').first()).toContainText('MD EDITOR 777');
  await page.locator('.history-item').first().click();
  await page.getByRole('button',{name:'Preparar correo'}).click();
  await expect(page.locator('.email-preview strong').filter({hasText:'Texto de correo personalizado'})).toHaveCount(1);
  await expect(editor).toContainText('Texto de correo personalizado');
  await page.getByRole('button',{name:'Regenerar desde los datos'}).click();
  await page.getByRole('button',{name:'Regenerar',exact:true}).click();
  await expect(editor).toContainText('Entorno SQL:');
  await page.screenshot({path:'../../work/editor-rich.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

